"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'honda'? I predict False.");
console.log(car === 'honda');
console.log("Is car !== 'toyota'? I predict True.");
console.log(car !== 'toyota');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car > 'honda'? I predict True.");
console.log(car > 'honda');
console.log("Is car < 'toyota'? I predict True.");
console.log(car < 'toyota');
